#! /bin/bash
MONO_VERSION=$1
MONO_DIR="mono-$MONO_VERSION"
echo "Downloading $MONO_VERSION"

wget http://download.mono-project.com/sources/mono/mono-$MONO_VERSION.tar.bz2

tar -jxf mono-$MONO_VERSION.tar.bz2
TARGET_DIR=`pwd`/mono

cd $MONO_DIR
pwd
echo $TARGET_DIR
./configure --prefix=$TARGET_DIR
make
make install
cd -

sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/*

dpkg-buildpackage -uc -us -b




