#! /bin/bash
set -e

die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "Please specify the version of Mono you want to build as the argument. (Check the tarball list here: http://download.mono-project.com/sources/mono/)"

MONO_VERSION=$1
MONO_DIR="mono-$MONO_VERSION"
echo "Downloading $MONO_VERSION"

wget http://download.mono-project.com/sources/mono/mono-$MONO_VERSION.tar.bz2

tar -jxf mono-$MONO_VERSION.tar.bz2
TARGET_DIR=`pwd`/mono

# this patch has been committed upstream and will be part of 3.0.4 out of the box; we need it now for 3.0.3 though so it becomes 3.0.3.1
if [ "$MONO_VERSION" = "3.0.3" ]
then
	git clone git://gitorious.7digital.local/sevendigital-api-inbox/deployment.git
	echo --patching mono
	cd $MONO_DIR && patch -p1 -i ../deployment/bootstrap/0001-System.Data.SqlClient-Support-for-Connection-Lifetim.patch && cd .. && rm -rf deployment
fi

cd $MONO_DIR
pwd
echo $TARGET_DIR
./configure --prefix=$TARGET_DIR
make
make install
cd -

sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/mcs
sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/xbuild
sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/nunit-console
sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/nunit-console2
sed -i s,`pwd`/mono,/usr,g $TARGET_DIR/bin/nunit-console4

dpkg-buildpackage -uc -us -b




