Document: 7digital-mono
Title: Debian 7digital-mono Manual
Author: <insert document author here>
Abstract: This manual describes what 7digital-mono is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/7digital-mono/7digital-mono.sgml.gz

Format: postscript
Files: /usr/share/doc/7digital-mono/7digital-mono.ps.gz

Format: text
Files: /usr/share/doc/7digital-mono/7digital-mono.text.gz

Format: HTML
Index: /usr/share/doc/7digital-mono/html/index.html
Files: /usr/share/doc/7digital-mono/html/*.html
